# Generated by Django 3.1.7 on 2022-08-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_encurta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_short',
            field=models.CharField(max_length=200, unique=True, verbose_name='Link short'),
        ),
    ]
