# Generated by Django 3.1.7 on 2022-08-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_encurta', '0003_link_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplink',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
