# Generated by Django 3.1.7 on 2022-08-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_encurta', '0004_grouplink_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
